FROM node:18

# Arbetskatalog i containern (kan heta vad som helst)
WORKDIR /server

# Kopiera bara backendens package.json
COPY . ./

# Installera backendens dependencies
RUN npm install --production

# Kopiera backendens filer
COPY . .

# Fly.io sätter PORT automatiskt
ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "start.js"]
